config/routes.rb
Rails.application.routes.draw do
  resources :employees
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations'}
  resources :transactions do
  collection { post :import }
  end
  resources :employees do
  collection { post :import }
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'



  get  '/transactions' => 'transactions#index'
  get  '/employees' =>  'employees#index'

end

app/models/employee.rb
class Employee < ApplicationRecord


  def self.import(file)



    CSV.foreach(file.path, :headers => true, :col_sep => ';') do |row|
      if row.size < 2
          CSV.foreach(file.path, :headers => true, :col_sep => ',') do |row2|
            import2(row2)
          end
          break
      else
        import2(row)
      end

    end
  end

  def self.import2(row)
    t = Employee.new()
    t.employee_no = row[1]
    t.employee_name = row[2]
    t.date_of_birth = row[3]
    t.gender = row[4]
    t.primary_email_address = row[5]
    t.secondary_email_address = row[6]
    t.primary_contact_no = row[7]
    t.secondary_contact_no = row[8]
    t.permanent_address = row[9]
    t.unit = row[10]
    t.department = row[11]
    t.employee_type = row[12]
    t.employement_status = row[13]
    t.rank = row[14]
    t.original_assignment = row[15]

    t.save
  end

  def self.to_csv(options = {})
  CSV.generate(options) do |csv|
    csv << column_names
    all.each do |employee|
      csv << employee.attributes.values_at(*column_names)
      end
    end
  end


end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
    respond_to do |format|
      format.html
      format.csv { send_data @employees.to_csv }
      format.xls { send_data @employees.to_csv(col_sep: ";") }
    end
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    Employee.import(params[:file])
    redirect_to root_url, notice: "Employee Details imported."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:employee_no, :employee_name, :date_of_birth, :gender, :primary_email_address, :secondary_email_address, :primary_contact_no, :secondary_contact_no, :permanent_address, :unit, :department, :employee_type, :employement_status, :rank, :original_assignment)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_with(model: employee, local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :employee_no %>
    <%= form.number_field :employee_no, id: :employee_employee_no %>
  </div>

  <div class="field">
    <%= form.label :employee_name %>
    <%= form.text_field :employee_name, id: :employee_employee_name %>
  </div>

  <div class="field">
    <%= form.label :date_of_birth %>
    <%= form.date_select :date_of_birth, id: :employee_date_of_birth %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.text_field :gender, id: :employee_gender %>
  </div>

  <div class="field">
    <%= form.label :primary_email_address %>
    <%= form.text_field :primary_email_address, id: :employee_primary_email_address %>
  </div>

  <div class="field">
    <%= form.label :secondary_email_address %>
    <%= form.text_field :secondary_email_address, id: :employee_secondary_email_address %>
  </div>

  <div class="field">
    <%= form.label :primary_contact_no %>
    <%= form.number_field :primary_contact_no, id: :employee_primary_contact_no %>
  </div>

  <div class="field">
    <%= form.label :secondary_contact_no %>
    <%= form.number_field :secondary_contact_no, id: :employee_secondary_contact_no %>
  </div>

  <div class="field">
    <%= form.label :permanent_address %>
    <%= form.text_field :permanent_address, id: :employee_permanent_address %>
  </div>

  <div class="field">
    <%= form.label :unit %>
    <%= form.text_field :unit, id: :employee_unit %>
  </div>

  <div class="field">
    <%= form.label :department %>
    <%= form.text_field :department, id: :employee_department %>
  </div>

  <div class="field">
    <%= form.label :employee_type %>
    <%= form.text_field :employee_type, id: :employee_employee_type %>
  </div>

  <div class="field">
    <%= form.label :employement_status %>
    <%= form.text_field :employement_status, id: :employee_employement_status %>
  </div>

  <div class="field">
    <%= form.label :rank %>
    <%= form.text_field :rank, id: :employee_rank %>
  </div>

  <div class="field">
    <%= form.label :original_assignment %>
    <%= form.date_select :original_assignment, id: :employee_original_assignment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employees</h1>

<table>
  <thead>
    <tr>
      <th>Employee no</th>
      <th>Employee name</th>
      <th>Date of birth</th>
      <th>Gender</th>
      <th>Primary email address</th>
      <th>Secondary email address</th>
      <th>Primary contact no</th>
      <th>Secondary contact no</th>
      <th>Permanent address</th>
      <th>Unit</th>
      <th>Department</th>
      <th>Employee type</th>
      <th>Employement status</th>
      <th>Rank</th>
      <th>Original assignment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.employee_no %></td>
        <td><%= employee.employee_name %></td>
        <td><%= employee.date_of_birth %></td>
        <td><%= employee.gender %></td>
        <td><%= employee.primary_email_address %></td>
        <td><%= employee.secondary_email_address %></td>
        <td><%= employee.primary_contact_no %></td>
        <td><%= employee.secondary_contact_no %></td>
        <td><%= employee.permanent_address %></td>
        <td><%= employee.unit %></td>
        <td><%= employee.department %></td>
        <td><%= employee.employee_type %></td>
        <td><%= employee.employement_status %></td>
        <td><%= employee.rank %></td>
        <td><%= employee.original_assignment %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

<h2>Import Employee Details</h2>

<%= form_tag({:action => :import}, multipart: true) do %>
  <%= file_field_tag :file %>
  <%= submit_tag( "Import" ) %>
<% end %>

<p>
  Download:
  <%= link_to "CSV", employees_path(format: "csv") %>
  <%= link_to "Excel", employees_path(format: "xls") %>
</p>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Employee no:</strong>
  <%= @employee.employee_no %>
</p>

<p>
  <strong>Employee name:</strong>
  <%= @employee.employee_name %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @employee.date_of_birth %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @employee.gender %>
</p>

<p>
  <strong>Primary email address:</strong>
  <%= @employee.primary_email_address %>
</p>

<p>
  <strong>Secondary email address:</strong>
  <%= @employee.secondary_email_address %>
</p>

<p>
  <strong>Primary contact no:</strong>
  <%= @employee.primary_contact_no %>
</p>

<p>
  <strong>Secondary contact no:</strong>
  <%= @employee.secondary_contact_no %>
</p>

<p>
  <strong>Permanent address:</strong>
  <%= @employee.permanent_address %>
</p>

<p>
  <strong>Unit:</strong>
  <%= @employee.unit %>
</p>

<p>
  <strong>Department:</strong>
  <%= @employee.department %>
</p>

<p>
  <strong>Employee type:</strong>
  <%= @employee.employee_type %>
</p>

<p>
  <strong>Employement status:</strong>
  <%= @employee.employement_status %>
</p>

<p>
  <strong>Rank:</strong>
  <%= @employee.rank %>
</p>

<p>
  <strong>Original assignment:</strong>
  <%= @employee.original_assignment %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>