config/routes.rb
Rails.application.routes.draw do
  resources :employees
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations'}
  resources :transactions do
  collection { post :import }
  end
  resources :employees do
  collection { post :import }
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'



  get  '/transactions' => 'transactions#index'
  get  '/employees' =>  'employees#index'

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all
    respond_to do |format|
      format.html
      format.csv { send_data @transactions.to_csv }
      format.xls { send_data @transactions.to_csv(col_sep: ";") }
    end
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    Transaction.import(params[:file])
    redirect_to root_url, notice: "Transactions imported."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:TransactionNo, :ApplicationDate, :LeaveType, :LeaveStatus, :DevelopmentType, :DegreePursued, :Institution, :Location, :Country, :SponsorDonor, :LocalAbroad, :StartDate, :EndDate, :Duration, :ReportForDuty, :ReturnServiceObligation, :ReturnServiceObligationStatus)
    end
end

app/views/transactions/_form.html.erb
<%= form_with(model: transaction, local: true) do |form| %>
  <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :TransactionNo %>
    <%= form.text_field :TransactionNo, id: :transaction_TransactionNo %>
  </div>

  <div class="field">
    <%= form.label :ApplicationDate %>
    <%= form.text_field :ApplicationDate, id: :transaction_ApplicationDate %>
  </div>

  <div class="field">
    <%= form.label :LeaveType %>
    <%= form.text_field :LeaveType, id: :transaction_LeaveType %>
  </div>

  <div class="field">
    <%= form.label :LeaveStatus %>
    <%= form.text_field :LeaveStatus, id: :transaction_LeaveStatus %>
  </div>

  <div class="field">
    <%= form.label :DevelopmentType %>
    <%= form.text_field :DevelopmentType, id: :transaction_DevelopmentType %>
  </div>

  <div class="field">
    <%= form.label :DegreePursued %>
    <%= form.text_field :DegreePursued, id: :transaction_DegreePursued %>
  </div>

  <div class="field">
    <%= form.label :Institution %>
    <%= form.text_field :Institution, id: :transaction_Institution %>
  </div>

  <div class="field">
    <%= form.label :Location %>
    <%= form.text_field :Location, id: :transaction_Location %>
  </div>

  <div class="field">
    <%= form.label :Country %>
    <%= form.text_field :Country, id: :transaction_Country %>
  </div>

  <div class="field">
    <%= form.label :SponsorDonor %>
    <%= form.text_field :SponsorDonor, id: :transaction_SponsorDonor %>
  </div>

  <div class="field">
    <%= form.label :LocalAbroad %>
    <%= form.text_field :LocalAbroad, id: :transaction_LocalAbroad %>
  </div>

  <div class="field">
    <%= form.label :StartDate %>
    <%= form.text_field :StartDate, id: :transaction_StartDate %>
  </div>

  <div class="field">
    <%= form.label :EndDate %>
    <%= form.text_field :EndDate, id: :transaction_EndDate %>
  </div>

  <div class="field">
    <%= form.label :Duration %>
    <%= form.text_field :Duration, id: :transaction_Duration %>
  </div>

  <div class="field">
    <%= form.label :ReportForDuty %>
    <%= form.text_field :ReportForDuty, id: :transaction_ReportForDuty %>
  </div>

  <div class="field">
    <%= form.label :ReturnServiceObligation %>
    <%= form.text_field :ReturnServiceObligation, id: :transaction_ReturnServiceObligation %>
  </div>

  <div class="field">
    <%= form.label :ReturnServiceObligationStatus %>
    <%= form.text_field :ReturnServiceObligationStatus, id: :transaction_ReturnServiceObligationStatus %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Transactions</h1>

<table>
  <thead>
    <tr>
      <th>Transactionno</th>
      <th>Applicationdate</th>
      <th>Leavetype</th>
      <th>LeaveDetails</th>
      <th>Leavestatus</th>
      <th>Developmenttype</th>
      <th>Degreepursued</th>
      <th>Institution</th>
      <th>Location</th>
      <th>Country</th>
      <th>Sponsordonor</th>
      <th>Localabroad</th>
      <th>Startdate</th>
      <th>Enddate</th>
      <th>Duration</th>
      <th>Reportforduty</th>
      <th>Returnserviceobligation</th>
      <th>Returnserviceobligationstatus</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.TransactionNo %></td>
        <td><%= transaction.ApplicationDate %></td>
        <td><%= transaction.LeaveType %></td>
        <td><%= transaction.LeaveDetails %></td>
        <td><%= transaction.LeaveStatus %></td>
        <td><%= transaction.DevelopmentType %></td>
        <td><%= transaction.DegreePursued %></td>
        <td><%= transaction.Institution %></td>
        <td><%= transaction.Location %></td>
        <td><%= transaction.Country %></td>
        <td><%= transaction.SponsorDonor %></td>
        <td><%= transaction.LocalAbroad %></td>
        <td><%= transaction.StartDate %></td>
        <td><%= transaction.EndDate %></td>
        <td><%= transaction.Duration %></td>
        <td><%= transaction.ReportForDuty %></td>
        <td><%= transaction.ReturnServiceObligation %></td>
        <td><%= transaction.ReturnServiceObligationStatus %></td>
        <td><%= link_to 'Show', transaction %></td>
        <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
        <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction', new_transaction_path %>

<h2>Import Transactions</h2>

<%= form_tag({:action => :import}, multipart: true) do %>
  <%= file_field_tag :file %>
  <%= submit_tag( "Import" ) %>
<% end %>

<p>
  Download:
  <%= link_to "CSV", transactions_path(format: "csv") %>
  <%= link_to "Excel", transactions_path(format: "xls") %>
</p>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Transactionno:</strong>
  <%= @transaction.TransactionNo %>
</p>

<p>
  <strong>Applicationdate:</strong>
  <%= @transaction.ApplicationDate %>
</p>

<p>
  <strong>Leavetype:</strong>
  <%= @transaction.LeaveType %>
</p>

<p>
  <strong>Leavedetails:</strong>
  <%= @transaction.LeaveDetails %>
</p>

<p>
  <strong>Leavestatus:</strong>
  <%= @transaction.LeaveStatus %>
</p>

<p>
  <strong>Developmenttype:</strong>
  <%= @transaction.DevelopmentType %>
</p>

<p>
  <strong>Degreepursued:</strong>
  <%= @transaction.DegreePursued %>
</p>

<p>
  <strong>Institution:</strong>
  <%= @transaction.Institution %>
</p>

<p>
  <strong>Location:</strong>
  <%= @transaction.Location %>
</p>

<p>
  <strong>Country:</strong>
  <%= @transaction.Country %>
</p>

<p>
  <strong>Sponsordonor:</strong>
  <%= @transaction.SponsorDonor %>
</p>

<p>
  <strong>Localabroad:</strong>
  <%= @transaction.LocalAbroad %>
</p>

<p>
  <strong>Startdate:</strong>
  <%= @transaction.StartDate %>
</p>

<p>
  <strong>Enddate:</strong>
  <%= @transaction.EndDate %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @transaction.Duration %>
</p>

<p>
  <strong>Reportforduty:</strong>
  <%= @transaction.ReportForDuty %>
</p>

<p>
  <strong>Returnserviceobligation:</strong>
  <%= @transaction.ReturnServiceObligation %>
</p>

<p>
  <strong>Returnserviceobligationstatus:</strong>
  <%= @transaction.ReturnServiceObligationStatus %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>